#!/bin/bash -e

rm -rf build
mkdir -p build/{main,test}
hh_client
h2tp src/main/hack build/main/hack
h2tp src/test/hack build/test/hack
if [ -e src/main/php ]; then cp -R src/main/php build/main/php; fi
if [ -e src/test/php ]; then cp -R src/test/php build/test/php; fi
vendor/bin/phpunit --bootstrap build/main/php/bootstrap.php build/test
