#!/bin/bash -e

(cd ~/projects/rose && stack build)

rm -rf build/{main,test}

mkdir -p build/{main,test,intermediate/{main,test}}

(
    cd src
    for f in $(find . -name '*.hh' -o -name '*.hhi'); do
        mkdir -p "../build/intermediate/$(dirname "$f")"
        cat "$f" | ../tools/steps.pl > "../build/intermediate/$f"
    done
    for f in $(find . -name '*.rose'); do
        mkdir -p "../build/intermediate/$(dirname "$f")"
        cat "$f" | (cd ~/projects/rose && stack exec rosec) > "../build/intermediate/${f%.rose}.hh"
    done
)

(
    cd build/intermediate
    touch .hhconfig
    hh_client
    h2tp main/hack ../main/hack
    h2tp test/hack ../test/hack
)

if [ -e src/main/php ]; then cp -R src/main/php build/main/php; fi
if [ -e src/test/php ]; then cp -R src/test/php build/test/php; fi
vendor/bin/phpunit --bootstrap build/main/php/bootstrap.php build/test
